version: '3.3'
services:
    phinix:
        build: .
        container_name: phinix
        restart: always
        ports:
            - '16200:16200/udp'
        volumes:
            - phinix_data:/data
            - ./extensions:/app/UserExtensions

volumes:
  phinix_data:
    driver: local
