name: Publish docker image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build_and_push:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Pull repo
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Log in to Docker Hub
      uses: docker/login-action@master
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Extract tags
      id: tags
      uses: docker/metadata-action@master
      with:
        images: hunyuan23333/phinix-rework
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=semver,pattern={{version}}

    - name: Publish to Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.tags.outputs.tags }}
